### ISSUE TITLE
Collection & Detail Pagination

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/tooling.report#130]
Similar to how the breadcrumbs work, at the bottom of a collection or detail page we should show next/prev links so the learning can continue within category. I think it should be cyclical, aka there's no "end." Open to ideas here!

<img width="1089" alt="Screen Shot 2020-04-07 at 2 46 04 PM" src="https://user-images.githubusercontent.com/1134620/78724308-02044e00-78e2-11ea-873c-57682cbca511.png">

**Comment by AbdoliMR** [comment]
Dear @argyleink
can I do it?

**Comment by argyleink** [comment]
fo sho @HERBOD7!
what do you need from us/me to feel empowered to get started?

**Comment by AbdoliMR** [comment]
> fo sho @HERBOD7!
> what do you need from us/me to feel empowered to get started?

Dear @argyleink 
thanks.
what's your opinion to fix the issue?
and which directory should I do it?

**Comment by argyleink** [comment]
> to fix the issue

Each test detail page should at minimum have links to the next and previous tests within the same category

> which directory?

`static-build/pages/test/index.tsx` line ~190. Your new component will go there, something like `</TestPagination test={test}>`. For inspiration and a kick start, checkout [TestCrumbs](https://github.com/GoogleChromeLabs/tooling.report/blob/dev/static-build/components/TestCrumbs/index.tsx), which already has lots of the data work done and is being used in the test detail page already. Create this new pagination component in the `static-build/components/` directory, next to TestCrumbs.

sorry for the delayed response!

**Comment by deepanshu44** [comment]
Hello @argyleink , is this issue still active? Can I look onto this and maybe work if its not that hard?

**Comment by argyleink** [comment]
Still active yep! It's middle level difficulty, but ask lots of questions, we can help you keep momentum.

**Comment by deepanshu44** [comment]
Thanks, @argyleink, :-) 
After studying the project, I think maybe we need to pass two new attributes called "prev" and "next" in  the component which renders a test page.
For example, in `addTestPage` function in `/static-build/index.tsx`, there is a `forof` loop,
 and now if we want to create "prev/next" links, we will need index ( that would get the previous entry in entries array) and for that we want `forEach` function such that
`Object.entries(tests).forEach(([testPath,path],i)=>{/**code**/})`.

I believe the same pattern would be repeated for subTests as well.
Need your suggestion on this. 
Thanks

**Comment by argyleink** [comment]
Sounds like the right place to start! I'm on vacation so will be slow to respond.

**Comment by deepanshu44** [comment]
@argyleink ok, I'm on it. BTW if you are on vacation then try to disconnect completely from internet and phone. Just saying.

**Comment by deepanshu44** [comment]
@argyleink just an update, pagination is working and only UI remains. I would be implementing the UI the same way as you've  shown in the image and sending a PR for you to review.

Below is working example
![Screencast from 21-12-21 08:11:40 PM IST_1](https://user-images.githubusercontent.com/62979448/146949184-575ab753-8a39-49c2-a984-cb0c6f992b5f.gif)

**Comment by deepanshu44** [comment]
@argyleink sorry to bother you again, but I need to know how the metadata for tests should be displayed in pagination links in mobile, should they be hidden, or font style be decreased to make space. Expecting reply after your vacation
![Screenshot](https://user-images.githubusercontent.com/62979448/147041737-9d286c86-548c-40a9-8c46-ef2d3be21dd5.jpg)

**Comment by argyleink** [comment]
exciting! thanks for sharing and hacking on this 🙂

**Comment by deepanshu44** [comment]
@argyleink I am really sorry for being late, I postponed it a bit. I am working on it right now.

**Comment by deepanshu44** [comment]
@argyleink Also I would like to ask which option from the ones listed below you will prefer-
"A" has less code but isn't readable much, I believe.
"B" has duplicate code but more readable.
How do you decide which one to choose? Do you know a better way?

**A.**
```css
.container {
   width:100%;
  &  >  .svgL, .svgR {
       width: 80px;                                                                                                   
       align-self: center;                                                                                            
       fill: aliceblue;   
}

.svgL{
    transform: rotate(90deg);
}

.svgR{
     transform: rotate(-90deg);
}
```
**B.**
```css
.container {
     width:100%;
}

.svgL{
       width: 80px;                                                                                                   
       align-self: center;                                                                                            
       fill: aliceblue;   
       transform: rotate(90deg);
}

.svgR{
       width: 80px;                                                                                                   
       align-self: center;                                                                                            
       fill: aliceblue;   
       transform: rotate(-90deg);
}
```
Thanks
